### PR TITLE
Fix toolbar not showing

### PR DESCRIPTION
**Pull request by chimosky**
Toolbar now shows but the game levels seems to be unstable, switching between Easy and Medium interchanges them sometimes so if you switched to Easy on game start then switched to Medium, the gamespeed of Medium is that of Easy and Easy is that of Medium.

### CODE REVIEW

**Comment by Dimi20cen** [comment]
I can't seem to replicate this issue, in which cases does the toolbar not showing?

**Comment by chimosky** [comment]
Start activity with your current changes and this is what it looks like - with the toolbar hidden - ;
Screenshot from 2023-08-01 14-43-00

With my changes, it looks like this;

Screenshot from 2023-08-01 14-44-07

**Comment by Dimi20cen** [comment]
When I run the activity with "sugar-activity3 . " or from the vm, the toolbar appears as expected. I can't find a reason for that difference. Could it be an issue with my setup?

**Comment by chimosky** [comment]
> When I run the activity with "sugar-activity3 . " or from the vm, the toolbar appears as expected. I can't find a reason for that difference. Could it be an issue with my setup?

How are you running sugar?

**Comment by Dimi20cen** [comment]
My vm is running with "sugar-live-build-20201217.hybrid.iso". Is that what you mean?

**Pull request closed without merging**
